// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHMNcXhCZiJjoIWlh6lCNN31b-QtVU_5A',
    appId: '1:1086471980039:web:e6e65771ef51e3e47e96a2',
    messagingSenderId: '1086471980039',
    projectId: 'flutterdanentang01',
    authDomain: 'flutterdanentang01.firebaseapp.com',
    storageBucket: 'flutterdanentang01.firebasestorage.app',
    measurementId: 'G-TF1TZN6VKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-CE6_bR2A5g_niixeVb_NHiEogkwBBQ8',
    appId: '1:1086471980039:android:d9cd9641fe2779727e96a2',
    messagingSenderId: '1086471980039',
    projectId: 'flutterdanentang01',
    storageBucket: 'flutterdanentang01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB83MOb9-7RS0JGaiD2JQ5LzoB9s07cWx8',
    appId: '1:1086471980039:ios:114271b4f70cd0237e96a2',
    messagingSenderId: '1086471980039',
    projectId: 'flutterdanentang01',
    storageBucket: 'flutterdanentang01.firebasestorage.app',
    iosBundleId: 'com.example.flutterDanentang01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB83MOb9-7RS0JGaiD2JQ5LzoB9s07cWx8',
    appId: '1:1086471980039:ios:114271b4f70cd0237e96a2',
    messagingSenderId: '1086471980039',
    projectId: 'flutterdanentang01',
    storageBucket: 'flutterdanentang01.firebasestorage.app',
    iosBundleId: 'com.example.flutterDanentang01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHMNcXhCZiJjoIWlh6lCNN31b-QtVU_5A',
    appId: '1:1086471980039:web:8d6e5dd64c670c087e96a2',
    messagingSenderId: '1086471980039',
    projectId: 'flutterdanentang01',
    authDomain: 'flutterdanentang01.firebaseapp.com',
    storageBucket: 'flutterdanentang01.firebasestorage.app',
    measurementId: 'G-2WG1TZFDNF',
  );
}
